LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_ARITH.ALL;
USE IEEE.STD_LOGIC_SIGNED.ALL;

ENTITY AD_DATA_TRANS IS 
PORT(
  CLK:IN STD_LOGIC;
  DIN:IN STD_LOGIC_VECTOR(11 DOWNTO 0);
  DOUT:OUT STD_LOGIC_VECTOR(11 DOWNTO 0)
);
END ENTITY;

ARCHITECTURE BEHAVE OF AD_DATA_TRANS IS 

BEGIN

  PROCESS IS BEGIN
  WAIT UNTIL RISING_EDGE(CLK);
    IF DIN < 2048 THEN
      DOUT <= DIN + 2048;
    ELSE
      DOUT <= DIN - 2048;
    END IF;
  END PROCESS;

END ARCHITECTURE;