LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_ARITH.ALL;
USE IEEE.STD_LOGIC_UNSIGNED.ALL;

ENTITY DAC_DATA_TRANS IS 
PORT(
  DIN_0:IN STD_LOGIC_VECTOR(11 DOWNTO 0);
  DIN_1:IN STD_LOGIC_VECTOR(11 DOWNTO 0);
  DADB_0:OUT STD_LOGIC_VECTOR(13 DOWNTO 0);
  DADB_1:OUT STD_LOGIC_VECTOR(13 DOWNTO 0)
);
END ENTITY;

ARCHITECTURE BEHAVE OF DAC_DATA_TRANS IS 

SIGNAL DIN_0_R:STD_LOGIC_VECTOR(11 DOWNTO 0):= (OTHERS => '0');
SIGNAL DIN_1_R:STD_LOGIC_VECTOR(11 DOWNTO 0):= (OTHERS => '0');

BEGIN

  DIN_0_R <= DIN_0 - 2048 WHEN DIN_0 >= 2048 ELSE
             DIN_0 + 2048;
  
  DIN_1_R <= DIN_1 - 2048 WHEN DIN_1 >= 2048 ELSE
             DIN_1 + 2048;  

  DADB_0 <= DIN_0_R & "00";
  
  DADB_1 <= DIN_1_R & "00";


END ARCHITECTURE;