LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_ARITH.ALL;
USE IEEE.STD_LOGIC_SIGNED.ALL;

ENTITY PHASE_DATA_TRANS IS 
GENERIC(
  WIDTH:INTEGER:= 25
);
PORT(
  DIN:IN STD_LOGIC_VECTOR(WIDTH - 1 DOWNTO 0);
  DOUT:OUT STD_LOGIC_VECTOR(11 DOWNTO 0)
);
END ENTITY;

ARCHITECTURE BEHAVE OF PHASE_DATA_TRANS IS

BEGIN

  DOUT <= CONV_STD_LOGIC_VECTOR(CONV_INTEGER(DIN),12);

END ARCHITECTURE;